### ISSUE TITLE
Update to latest version of fitnesse

### ISSUE THREAD

**Issue by haroon-sheikh** [sitture/fitnesse-quickstart#2]
## Task

- Update fitnesse archetype to use the latest version of fitnesse (The latest version of fitnesse is http://docs.fitnesse.org/.FrontPage.FitNesseDevelopment.FitNesseRelease20200501)
- Validate, we're still able to generate a project using this atchetype.
- And fitnesse can still be launched with mvn. See [README.md](https://github.com/sitture/fitnesse-quickstart/blob/master/README.md)

**Comment by ShehzadAhm** [comment]
Hi @haroon-sheikh, what exactly needs to be done? It would be helpful if you could elaborate.

**Comment by haroon-sheikh** [comment]
@ShehzadAhm I've updated the description above.
